site_name: ScrapeSome
theme:
  name: material
  features:
    - content.code.copy
  logo: assets/images/favicon.png
  favicon: assets/images/favicon.png
  palette:
    primary: green
    accent: black
nav:
  - Home: index.md
  - About: about.md
  - Getting Started: getting-started.md
  - Advanced Usage: usage.md
  - Environment Configuration: config.md
  - Output Formats: output-formats.md
  - CLI: cli.md 
  - Examples: examples.md
  - Licence: licence.md
  - Contribution: contribution.md
  - File Saving: file-saving.md
extra:
  social_image: assets/images/favicon.png